# Generated by Django 4.0.1 on 2022-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('play_time', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=200)),
                ('justwatch_rating', models.CharField(max_length=10)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('synopsis', models.TextField(max_length=500)),
                ('poster', models.CharField(max_length=100)),
                ('genre_list', models.ManyToManyField(to='movies.MovieType')),
            ],
            options={
                'verbose_name': 'movie',
                'db_table': 'movie',
            },
        ),
    ]
