# Generated by Django 4.0.2 on 2022-02-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre_list',
            field=models.ManyToManyField(related_name='genre_list_M2M', to='movies.MovieType'),
        ),
    ]
